export const CATEGORIES = [
  'Nature', 'Historical', 'Cultural', 'Adventure', 'Spiritual', 'Urban', 'Festivals',
]

export const destinations = [
  {
    id: 'aburi-botanical-gardens',
    name: 'Aburi Botanical Gardens',
    region: 'Eastern',
    category: 'Nature',
    description:
      "Located in the cool hills above Accra, the Aburi Botanical Gardens were established in 1890 by the British colonial administration. Spanning over 64 hectares, the gardens house a remarkable collection of tropical plants, trees, and flowers. The refreshing mountain climate makes it a popular escape from the heat of Accra. Visitors can stroll through shaded pathways, admire exotic tropical plants, and enjoy breathtaking views of the surrounding landscape.",
    shortDescription: 'Established in 1890, these stunning colonial gardens span 64 hectares of tropical flora in the cool Akuapim Hills.',
    image: '/assets/aburi-botanical-gardens.jpg',
    gallery: [
      '/assets/aburi-botanical-gardens.jpg',
      '/assets/aburi-2.png',
      '/assets/mountain-forest.jpg',
      '/assets/grasroot.jpg',
    ],
    location: 'Aburi, Eastern Region',
    highlights: ['Over 600 plant species', 'Colonial-era architecture', 'Cool mountain climate', 'Scenic hiking trails'],
    bestTime: 'October to April',
    entryFee: 'GHS 10 adults / GHS 5 children',
    activities: ['Nature walks', 'Photography', 'Picnicking', 'Bird watching'],
  },
  {
    id: 'kakum-national-park',
    name: 'Kakum National Park',
    region: 'Central',
    category: 'Nature',
    description:
      "Kakum National Park is one of West Africa's most celebrated rainforest conservation areas. The park is renowned for its 333-metre canopy walkway suspended up to 30 metres above the forest floor. The park protects forest elephants, leopards, over 400 butterfly species, and more than 200 bird species. The dense rainforest provides a truly immersive natural experience unlike anywhere else in Ghana.",
    shortDescription: 'Home to a thrilling 333m canopy walkway 30m above the rainforest, protecting elephants and 400+ butterfly species.',
    image: '/assets/kakum-national-park.png',
    gallery: [
      '/assets/kakum-national-park.png',
      '/assets/kakum-3.jpg',
      '/assets/mountain-forest.jpg',
      '/assets/aburi-2.png',
    ],
    location: 'Cape Coast, Central Region',
    highlights: ['333m canopy walkway', 'Forest elephants', '400+ butterfly species', '200+ bird species'],
    bestTime: 'November to April',
    entryFee: 'GHS 120 adults (includes canopy walk)',
    activities: ['Canopy walkway', 'Wildlife tours', 'Bird watching', 'Guided jungle walks'],
  },
  {
    id: 'cape-coast-castle',
    name: 'Cape Coast Castle',
    region: 'Central',
    category: 'Historical',
    description:
      "Cape Coast Castle is one of the most significant UNESCO World Heritage Sites in West Africa. Built by the Swedish in the 1650s, it served as a major holding point during the transatlantic slave trade. The castle's dungeons, where thousands of enslaved people were held before being shipped to the Americas, are a sobering and deeply emotional experience. Today it functions as a powerful museum of remembrance.",
    shortDescription: 'A UNESCO World Heritage Site and former slave trading post — a profound journey through Africa\'s most painful historical chapter.',
    image: '/assets/lkb.jpg',
    gallery: [
      '/assets/lkb.jpg',
      '/assets/hoooo.jpg',
      '/assets/rxgggg.jpg',
      '/assets/courtyard.jpg',
    ],
    location: 'Cape Coast, Central Region',
    highlights: ['UNESCO World Heritage Site', 'Slave dungeons', 'Door of No Return', 'Museum exhibits'],
    bestTime: 'Year round',
    entryFee: 'GHS 50 adults / GHS 25 children',
    activities: ['Guided historical tours', 'Museum visits', 'Photography', 'Reflection walks'],
  },
  {
    id: 'lake-volta',
    name: 'Lake Volta',
    region: 'Volta',
    category: 'Nature',
    description:
      "Lake Volta is the world's largest man-made lake by surface area, covering approximately 8,502 square kilometres. Created by the Akosombo Dam in 1965, the lake provides hydroelectric power for Ghana and much of West Africa. Stunning boat tours, fishing adventures, and the communities that depend on the lake for their livelihoods make it both an ecological wonder and a cultural cornerstone of Ghanaian life.",
    shortDescription: "The world's largest man-made lake by surface area — offering boat tours, fishing, and breathtaking sunset views.",
    image: '/assets/lake-volta.png',
    gallery: [
      '/assets/lake-volta.png',
      '/assets/sogakope.png',
      '/assets/rxgggg.jpg',
      '/assets/photo5.jpg',
    ],
    location: 'Akosombo, Volta Region',
    highlights: ["World's largest man-made lake", 'Akosombo Dam', 'Fishing villages', 'Sunset cruises'],
    bestTime: 'November to March',
    entryFee: 'Free (boat tours vary)',
    activities: ['Boat cruises', 'Fishing', 'Photography', 'Swimming'],
  },
  {
    id: 'boti-falls',
    name: 'Boti Falls',
    region: 'Eastern',
    category: 'Nature',
    description:
      "Boti Falls is a magnificent twin waterfall in the Boti Forest Reserve of Ghana's Eastern Region. The falls are celebrated for being the male and female waterfalls — during the rainy season they merge into one spectacular cascade. The surrounding forest is lush and home to diverse wildlife. The nearby Umbrella Rock offers climbers stunning panoramic views of the landscape.",
    shortDescription: 'Twin waterfalls known as male and female that merge spectacularly during the rainy season in the lush Boti Forest Reserve.',
    image: '/assets/boti-falls.png',
    gallery: [
      '/assets/boti-falls.png',
      '/assets/asenema-falls.jpg',
      '/assets/mountain-forest.jpg',
      '/assets/rock.jpg',
    ],
    location: 'Boti, Eastern Region',
    highlights: ['Twin waterfalls', 'Umbrella Rock nearby', 'Forest hiking', 'Natural swimming pools'],
    bestTime: 'June to November (rainy season)',
    entryFee: 'GHS 20 adults',
    activities: ['Waterfall viewing', 'Rock climbing', 'Nature walks', 'Swimming'],
  },
  {
    id: 'asenema-falls',
    name: 'Asenema Falls',
    region: 'Western',
    category: 'Nature',
    description:
      "Asenema Falls is one of Ghana's hidden gems — a breathtaking multi-tiered waterfall tucked within the Western Region's dense tropical forest. The cascades flow down through pristine jungle trails, creating natural swimming pools at the base. Relatively undiscovered by mass tourism, this site offers an authentic and peaceful natural retreat for the adventurous traveller.",
    shortDescription: "A multi-tiered cascade through pristine jungle with natural swimming pools — one of Ghana's hidden natural gems.",
    image: '/assets/asenema-falls.jpg',
    gallery: [
      '/assets/asenema-falls.jpg',
      '/assets/boti-falls.png',
      '/assets/mountain-forest.jpg',
      '/assets/lnuio.jpg',
    ],
    location: 'Asenema, Western Region',
    highlights: ['Multi-tiered cascades', 'Natural swimming pools', 'Jungle trails', 'Unspoiled scenery'],
    bestTime: 'July to October',
    entryFee: 'GHS 15 adults',
    activities: ['Waterfall trekking', 'Swimming', 'Photography', 'Jungle exploration'],
  },
  {
    id: 'nzulenzu',
    name: 'Nzulenzu',
    region: 'Western',
    category: 'Cultural',
    description:
      "Nzulenzu is a remarkable stilt village built entirely on Lake Tadane in the Western Region. Inhabited by the Nzema people for centuries, this unique community is accessible only by canoe. Homes, schools, a church, and even a palace are all built on wooden stilts above the water, showcasing a sustainable way of life in perfect harmony with the lake environment. It is a UNESCO tentative World Heritage Site.",
    shortDescription: 'A unique stilt village built entirely on water, accessible only by canoe, showcasing centuries of Nzema culture.',
    image: '/assets/nzulenzu.jpg',
    gallery: [
      '/assets/nzulenzu.jpg',
      '/assets/lake-volta.png',
      '/assets/rxgggg.jpg',
      '/assets/sogakope.png',
    ],
    location: 'Beyin, Western Region',
    highlights: ['UNESCO tentative heritage', 'Stilt village on water', 'Canoe-only access', 'Living Nzema culture'],
    bestTime: 'October to March',
    entryFee: 'GHS 60 including canoe ride',
    activities: ['Canoe tour', 'Cultural immersion', 'Photography', 'Village walk'],
  },
  {
    id: 'mole-national-park',
    name: 'Mole National Park',
    region: 'Northern',
    category: 'Nature',
    description:
      "Mole National Park is Ghana's largest wildlife sanctuary, covering over 4,840 square kilometres of savanna woodland. It is home to the largest elephant population in Ghana, as well as hippos, buffalos, warthogs, baboons, and over 300 bird species. Walking safaris led by armed rangers bring visitors face-to-face with wildlife in one of Africa's most affordable and intimate safari experiences.",
    shortDescription: "Ghana's largest national park — affordable walking safaris with elephants, hippos, and 300+ bird species.",
    image: '/assets/tour-sites.jpg',
    gallery: [
      '/assets/tour-sites.jpg',
      '/assets/tourist-location.png',
      '/assets/mountain-forest.jpg',
      '/assets/grasroot.jpg',
    ],
    location: 'Damongo, Northern Region',
    highlights: ["Ghana's largest park", 'Elephant populations', 'Walking safaris', '300+ bird species'],
    bestTime: 'December to April',
    entryFee: 'GHS 80 adults',
    activities: ['Walking safari', 'Game drives', 'Bird watching', 'Photography'],
  },
  {
    id: 'larabanga-mosque',
    name: 'Larabanga Mosque',
    region: 'Northern',
    category: 'Spiritual',
    description:
      "The Larabanga Mosque is one of the oldest mosques in West Africa, believed to have been built in 1421. This ancient Sudanese-style mud mosque, characterised by its protruding wooden beams and white-plastered walls, stands as a testament to the region's Islamic heritage. It remains an active place of worship and is located near Mole National Park, making it an ideal stop on a northern Ghana itinerary.",
    shortDescription: "Built in 1421, this is one of West Africa's oldest mosques — a stunning example of Sudanese mud architecture.",
    image: '/assets/mosque.jpg',
    gallery: [
      '/assets/mosque.jpg',
      '/assets/ghana-photo.jpg',
      '/assets/courtyard.jpg',
      '/assets/lnuio.jpg',
    ],
    location: 'Larabanga, Northern Region',
    highlights: ['Built in 1421', 'Sudanese mud architecture', 'Active place of worship', 'Near Mole National Park'],
    bestTime: 'November to April',
    entryFee: 'Donation appreciated',
    activities: ['Historical tours', 'Photography', 'Cultural learning', 'Prayer observance'],
  },
  {
    id: 'umbrella-rock',
    name: 'Umbrella Rock',
    region: 'Upper East',
    category: 'Adventure',
    description:
      "Umbrella Rock in Tongo is a geological marvel — a massive boulder perfectly balanced atop another rock, creating a natural umbrella shape. This striking formation is an iconic landmark of northern Ghana. The surrounding Tongo Hills are rich with ancient rock formations, caves, and the traditional shrines of the Tallensi people, offering excellent hiking and a deep connection with indigenous spiritual traditions.",
    shortDescription: 'A geological marvel — a massive boulder balanced atop another rock, surrounded by the sacred Tongo Hills.',
    image: '/assets/umbrella-rock.jpg',
    gallery: [
      '/assets/umbrella-rock.jpg',
      '/assets/rock.jpg',
      '/assets/mountain-forest.jpg',
      '/assets/tourist-location.png',
    ],
    location: 'Tongo, Upper East Region',
    highlights: ['Natural rock formation', 'Tongo Hills', 'Tallensi cultural sites', 'Rock climbing'],
    bestTime: 'October to March',
    entryFee: 'GHS 20 adults',
    activities: ['Rock climbing', 'Hiking', 'Photography', 'Cultural tours'],
  },
  {
    id: 'independence-arch',
    name: 'Independence Arch',
    region: 'Greater Accra',
    category: 'Historical',
    description:
      "The Independence Arch in Accra's Black Star Square is one of Ghana's most iconic national monuments, built to commemorate independence from British colonial rule on March 6, 1957. Bearing the inscription 'Freedom and Justice', the arch stands proudly in Black Star Square — one of the largest public squares in the world — and serves as the venue for Ghana's most important national ceremonies and celebrations.",
    shortDescription: "Ghana's most iconic monument marking the 1957 independence, set within Black Star Square — one of the world's largest public squares.",
    image: '/assets/mmmm.jpg',
    gallery: [
      '/assets/mmmm.jpg',
      '/assets/accra-ghana.jpg',
      '/assets/fyjk.jpg',
      '/assets/courtyard.jpg',
    ],
    location: 'Accra, Greater Accra',
    highlights: ['March 6 1957 independence', '"Freedom and Justice"', 'Black Star Square', 'National ceremonies'],
    bestTime: 'Year round',
    entryFee: 'Free',
    activities: ['Sightseeing', 'Photography', 'Historical tours', 'Independence Day events'],
  },
  {
    id: 'labadi-beach',
    name: 'Labadi Beach',
    region: 'Greater Accra',
    category: 'Urban',
    description:
      "Labadi Beach (La Pleasure Beach) is the most popular beach in Accra and one of the finest in West Africa. This vibrant stretch of golden sand is lined with bars, restaurants, and entertainment. On weekends it transforms into a lively cultural hub with live music, traditional drumming, and dancing. Horse riding, swimming, and the energy of Accra's urban life make this a must-visit destination.",
    shortDescription: "Accra's most vibrant beach — golden sands with live music, traditional drumming, and the lively energy of urban Ghana.",
    image: '/assets/gcnhh.jpg',
    gallery: [
      '/assets/gcnhh.jpg',
      '/assets/photo5.jpg',
      '/assets/accra-ghana.jpg',
      '/assets/fyjk.jpg',
    ],
    location: 'La, Greater Accra',
    highlights: ['Golden sandy beach', 'Live music & drumming', 'Beach bars & restaurants', 'Horse riding'],
    bestTime: 'October to March',
    entryFee: 'GHS 15 adults',
    activities: ['Swimming', 'Beach parties', 'Horse riding', 'Music & dance'],
  },
]
